DROP TABLE GENRES IF EXISTS;
DROP TABLE AUTHORS IF EXISTS;
DROP TABLE BOOKS IF EXISTS;
CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL
);
CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIO VARCHAR(255) NOT NULL ,
    Age INT
);
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    ID_Author BIGINT NOT NULL,
    ID_Genre BIGINT NOT NULL,
    FOREIGN KEY (ID_Author) REFERENCES AUTHORS (ID),
    FOREIGN KEY (ID_Genre) REFERENCES GENRES(ID)
);